name: "DocChain1"
description: "Generate modern documentation using Doxygen, Sphinx, Breathe, and Fumadocs"
on:
  [push, workflow_dispatch]
env:
  DOXYFILE_PATH: "../../docs/Doxyfile"
  DOXYGEN_WORKING_DIRECTORY: "./harmonize/cpp/"

jobs:
  generate_doxygen_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Doxygen Documentation
        uses: mattnotmitt/doxygen-action@v1.12
        with:
          doxyfile-path: ${{ env.DOXYFILE_PATH }}
          working-directory: ${{ env.DOXYGEN_WORKING_DIRECTORY }}
      - run: pwd && ls
      - name: Upload Generated XML
        uses: actions/upload-artifact@v4
        with:
          name: XML
          path: GeneratedDocumentation/xml
      - name: Upload Generated HTML
        uses: actions/upload-artifact@v4
        with:
          name: HTML
          path: GeneratedDocumentation/html
      - run: cd GeneratedDocumentation && ls
      - run: cd GeneratedDocumentation/xml && ls
      - run: cd GeneratedDocumentation/html && ls