name: "DocChain1"
description: "Generate modern documentation using Doxygen, Sphinx, Breathe, and Fumadocs"
on:
  [push, workflow_dispatch]
env:
  DOXYFILE_PATH: "./docs/Doxygen/Doxyfile"
  DOXYGEN_WORKING_DIRECTORY: "./"

  SPHINXOPTS: ""
  SPHINXBUILD: sphinx-build
  SOURCEDIR: "./docs/Sphinx/"
  BUILDDIR: "./GeneratedDocumentation"

jobs:
  generate_doxygen_documentation:
    runs-on: ubuntu-latest

    # Experimental Permissions of Test GitHub Pages Deployment
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # End Experimental Permissions

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Doxygen Documentation
        uses: mattnotmitt/doxygen-action@v1.12
        with:
          doxyfile-path: ${{ env.DOXYFILE_PATH }}
          working-directory: ${{ env.DOXYGEN_WORKING_DIRECTORY }}
      - name: Upload Generated XML
        uses: actions/upload-artifact@v4
        with:
          name: XML
          path: GeneratedDocumentation/xml
      - name: Upload Generated HTML
        uses: actions/upload-artifact@v4
        with:
          name: RAW_HTML
          path: GeneratedDocumentation/html
      - name: Test View
        run: cd GeneratedDocumentation/html && ls

      - name: Test - Upload Generated HTML, formatted for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: GeneratedDocumentation/html

      # - name: Test Configure GitHub Pages
      #   uses: actions/configure-pages@v5
      - name: Test Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment

  generate_sphinx_documentation:

    needs: generate_doxygen_documentation
    runs-on: ubuntu-latest

    # Experimental Permissions of Test GitHub Pages Deployment
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # End Experimental Permissions

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Sphinx
        run: pip install -U sphinx
      # - run: cd .. && ls
      - run: pwd
      - run: ls
      - run: cd docs && ls
      - name: Run Sphinx HTML Builder
        run: ${{ env.SPHINXBUILD }} -M html "${{ env.SOURCEDIR }}" "${{ env.BUILDDIR }}"
      - name: Upload Generated HTML
        uses: actions/upload-artifact@v4
        with:
          name: SphinxHTML
          path: ./GeneratedDocumentation/html
      
        # Test Deploy
      - name: Test - Upload Generated HTML, formatted for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: GeneratedDocumentation/html
      - name: Test Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment